### ISSUE TITLE
Publish to hex?

### ISSUE THREAD

**Issue by ctbucha** [techgaun/zxcvbn-elixir#2]
Hi there. I'm looking to use a zxcvbn library on my elixir app so that the password strength metrics are the same as my client code (which is also using zxcvbn), and this project seems like the furthest along to implement zxcvbn in elixir.

Any updates on when this project might be production ready or if you need any help getting it there?

**Comment by techgaun** [comment]
Hi @ctbucha I am aiming to finish the implementation and testing next week (03/20). I don't have as much time this week but I will be able to work on it next week. I have updated README to reflect that. I will probably create issues for community contribution after 3/20 for the things that will be missing but that will be minimal production-ready first version by then. I will also publish to hex at that time.

**Comment by techgaun** [comment]
@ctbucha I have a minimal working version however this doesn't include sequence and date matching as of now. My initial estimation for 03/20 is going to be impossible to hit because of priorities at my primary work so I am going to finish this by 03/24. 03/23 (Sunday) is when I have quite a bit of time to work on this. Just wanted to notify you about the status.

Feel free to give it a try at its current state if you want to.

**Comment by techgaun** [comment]
Update: Only date matching is needed to be implemented.

**Comment by techgaun** [comment]
The initial release has been published to hex. Feel free to give it a try. Closing

**Comment by techgaun** [comment]
@ctbucha I've released v. 0.1.2 to hex. This is ready to use in production and I would love to get feedback if possible. Thanks!
